# Generated by Django 6.0.6 on 2026-07-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority_weight',
        ),
    ]
