# Generated by Django 6.0.6 on 2026-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_comment_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_weight',
            field=models.IntegerField(default=0),
        ),
    ]
